[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
description = "Adds event that triggers when the game reaches 7 pm"
websiteUrl = "https://github.com/FelixAllard/LunarAnomaliesLC"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Evaisa-LethalLib = "0.15.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./Packages"

[[build.copy]]
source = "../bin/Release/netstandard2.1/TheWeavers.LunarAnomalies.dll"
target = "plugins/LunarAnomalies/"

[[build.copy]]
source = "./lunaranomaliesmodassets"
target = "plugins/LunarAnomalies/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
communities = [ "lethal-company", ]
[publish.categories]
# Get the list of categories from https://thunderstore.io/api/experimental/community/lethal-company/category/
lethal-company = [ "bepinex", "clientside", "serverside", "monsters", "mods", ]